var abilityarr = [
  {
    name: '',
    type: 'Untyped',
    tier: 0,
    bonushp: 0,
    bonusenergy: 0,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 0,
    roundreq: 0,
    typereq: false,
    successreq: false,
    offense: false,
    defense: false,
    condapply: [],
    condremove: [],
    abreak: 0,
    wbreak: 0,
    aboost: 0,
    wboost: 0,
    dmgmultiplier: 1,
    forwardbonus: 0,
    pmitigate: 0,
    mmitigate: 0,
    ignoremit: false,
    preflect: 0,
    mreflect: 0,
    usagelimit: 0,
  },
];

var initabilityarr = [
  {
    name: 'Analyze',
    type: 'Untyped',
    tier: 0,
    bonushp: 0,
    bonusenergy: 0,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 2,
    analyze: true,
    hpbump: 0,
    energybump: 0,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Energize',
    type: 'Untyped',
    tier: 2,
    bonushp: 0,
    bonusenergy: 3,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 0,
    analyze: false,
    hpbump: 0,
    energybump: 12,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Exhaust',
    type: 'Magical',
    tier: 3,
    bonushp: 1,
    bonusenergy: 1,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 1,
    bonusbase: 0,
    energycost: 2,
    analyze: false,
    hpbump: 0,
    energybump: 0,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 0.6,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Heal',
    type: 'Untyped',
    tier: 0,
    bonushp: 0,
    bonusenergy: 0,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 2,
    analyze: false,
    hpbump: 15,
    energybump: 0,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Intimidate',
    type: 'Physical',
    tier: 3,
    bonushp: 0,
    bonusenergy: 0,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 2,
    bonusbase: 1,
    energycost: 0,
    analyze: false,
    hpbump: 0,
    energybump: 0,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 0.8,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Protect',
    type: 'Magical',
    tier: 2,
    bonushp: 1,
    bonusenergy: 0,
    bonusarmor: 0,
    bonusward: 1,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 0,
    analyze: false,
    hpbump: 0,
    energybump: 0,
    abump: 0,
    wbump: 3,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Repair',
    type: 'Physical',
    tier: 2,
    bonushp: 1,
    bonusenergy: 0,
    bonusarmor: 1,
    bonusward: 0,
    bonusvariance: 0,
    bonusbase: 0,
    energycost: 0,
    analyze: false,
    hpbump: 0,
    energybump: 0,
    abump: 3,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 0,
    mvarianceshrink: 0
  },
  {
    name: 'Weaken',
    type: 'Magical',
    tier: 0,
    bonushp: 0,
    bonusenergy: 1,
    bonusarmor: 0,
    bonusward: 0,
    bonusvariance: 1,
    bonusbase: 1,
    energycost: 2,
    analyze: false,
    hpbump: 0,
    energybump: 0,
    abump: 0,
    wbump: 0,
    mdamagemultiplier: 1,
    menergymultiplier: 1,
    mbaseshrink: 1,
    mvarianceshrink: 1
  },

];




/*
//ability object definition:
ability = {
  name: '',
  type: 'Untyped',
  tier: 0,
  bonushp: 0,
  bonusenergy: 0,
  bonusarmor: 0,
  bonusward: 0,
  bonusvariance: 0,
  bonusbase: 0,
  energycost: 0,
  roundreq: 0,
  typereq: false,
  successreq: false,
  offense: false,
  defense: false,
  condapply: [],
  condremove: [],
  abreak: 0,
  wbreak: 0,
  aboost: 0,
  wboost: 0,
  dmgmultiplier: 1,
  forwardbonus: 0,
  pmitigate: 0,
  mmitigate: 0,
  ignoremit: false,
  preflect: 0,
  mreflect: 0,
  usagelimit: 0,
}
//init ability object definition:
initability = {
  name: '',
  type: 'Untyped',
  tier: 0,
  bonushp: 0,
  bonusenergy: 0,
  bonusarmor: 0,
  bonusward: 0,
  bonusvariance: 0,
  bonusbase: 0,
  energycost: 0,
  analyze: false,
  hpbump: 0,
  energybump: 0,
  abump: 0,
  wbump: 0,
  mdamagemultiplier: 1,
  mbaseshrink: 0,
  mvarianceshrink: 0
}
*/
