const monsterarr = [{
  name: 'Tiefling',
  illus: 'images/characters/tiefling.gif',
  maxhp: 15,
  currhp: 15,
  maxenergy: 20,
  currenergy: 20,
  dtype: 'Physical',
  basedmg: 5,
  dmgvariance: 3,
  maxarmor: 1,
  currarmor: 1,
  maxward: 1,
  currward: 1,
  abilqueue: ['Curse', 'Attack', 'Venom-Strike', 'Dodge', 'Attack'],
  evil: true,
}, {
  name: 'Crazed Gnome',
  illus: 'images/characters/crazed-gnome.gif',
  maxhp: 20,
  currhp: 20,
  maxenergy: 25,
  currenergy: 25,
  dtype: 'Magical',
  basedmg: 6,
  dmgvariance: 4,
  maxarmor: 0,
  currarmor: 0,
  maxward: 2,
  currward: 2,
  abilqueue: ['Mote-of-Fire', 'Silence', 'Flame-Wave', 'Drain-Life', 'Attack'],
  evil: false,
}, {
  name: 'Pit Fiend',
  illus: 'images/characters/pit-fiend.gif',
  maxhp: 45,
  currhp: 45,
  maxenergy: 18,
  currenergy: 18,
  dtype: 'Physical',
  basedmg: 8,
  dmgvariance: 6,
  maxarmor: 3,
  currarmor: 3,
  maxward: 1,
  currward: 1,
  abilqueue: ['Doom', 'Feint', 'Attack', 'Combo', 'Finisher'],
  evil: true,
}, {
  name: 'Goblin Archer',
  illus: 'images/characters/goblin-archer.gif',
  maxhp: 12,
  currhp: 12,
  maxenergy: 10,
  currenergy: 10,
  dtype: 'Physical',
  basedmg: 6,
  dmgvariance: 3,
  maxarmor: 0,
  currarmor: 0,
  maxward: 0,
  currward: 0,
  abilqueue: ['Opening-Volley', 'Attack', 'Piercing-Strike', 'Dodge', 'Attack'],
  evil: false,
}, {
  name: 'Goblin Berserker',
  illus: 'images/characters/goblin-berserker.gif',
  maxhp: 22,
  currhp: 22,
  maxenergy: 15,
  currenergy: 15,
  dtype: 'Physical',
  basedmg: 7,
  dmgvariance: 4,
  maxarmor: 2,
  currarmor: 2,
  maxward: 0,
  currward: 0,
  abilqueue: ['Armor-Break', 'Attack', 'Combo', 'Feint', 'Attack'],
  evil: false,
}, {
  name: 'Goblin Crone',
  illus: 'images/characters/goblin-crone.gif',
  maxhp: 17,
  currhp: 17,
  maxenergy: 20,
  currenergy: 20,
  dtype: 'Magical',
  basedmg: 6,
  dmgvariance: 5,
  maxarmor: 0,
  currarmor: 0,
  maxward: 4,
  currward: 4,
  abilqueue: ['Curse', 'Lightning-Bolt', 'Cold-Snap', 'Attack', 'Dodge'],
  evil: false,
}, {
  name: 'Imp',
  illus: 'images/characters/imp.gif',
  maxhp: 9,
  currhp: 9,
  maxenergy: 12,
  currenergy: 12,
  dtype: 'Magical',
  basedmg: 2,
  dmgvariance: 6,
  maxarmor: 1,
  currarmor: 1,
  maxward: 1,
  currward: 1,
  abilqueue: ['Mote-of-Fire', 'Cleanse', 'Mote-of-Fire', 'Attack', 'Attack'],
  evil: true,
}, {
  name: 'Rust Monster',
  illus: 'images/characters/rust-monster.gif',
  maxhp: 19,
  currhp: 19,
  maxenergy: 15,
  currenergy: 15,
  dtype: 'Physical',
  basedmg: 5,
  dmgvariance: 2,
  maxarmor: 2,
  currarmor: 2,
  maxward: 2,
  currward: 2,
  abilqueue: ['Armor-Break', 'Armor-Break', 'Attack', 'Feint', 'Attack'],
  evil: false,
}, {
  name: 'Wolferine',
  illus: 'images/characters/wolferine.gif',
  maxhp: 25,
  currhp: 25,
  maxenergy: 30,
  currenergy: 30,
  dtype: 'Physical',
  basedmg: 3,
  dmgvariance: 4,
  maxarmor: 1,
  currarmor: 1,
  maxward: 0,
  currward: 0,
  abilqueue: ['Feint', 'Attack', 'Combo', 'Piercing-Strike', 'Attack'],
  evil: false,
}, {
  name: 'Gelatinous Cube',
  illus: 'images/characters/gelatinous-cube.gif',
  maxhp: 30,
  currhp: 30,
  maxenergy: 12,
  currenergy: 12,
  dtype: 'Magical',
  basedmg: 8,
  dmgvariance: 3,
  maxarmor: 2,
  currarmor: 2,
  maxward: 3,
  currward: 3,
  abilqueue: ['Spell-Break', 'Cleanse', 'Attack', 'Attack', 'Attack'],
  evil: false,
}, {
  name: 'Skeleton',
  illus: 'images/characters/skeleton.gif',
  maxhp: 24,
  currhp: 24,
  maxenergy: 24,
  currenergy: 24,
  dtype: 'Physical',
  basedmg: 5,
  dmgvariance: 4,
  maxarmor: 3,
  currarmor: 3,
  maxward: 1,
  currward: 1,
  abilqueue: ['Attack', 'Combo', 'Attack', 'Combo', 'Block'],
  evil: true,
}, {
  name: 'Mercenary',
  illus: 'images/characters/mercenary.gif',
  maxhp: 30,
  currhp: 30,
  maxenergy: 24,
  currenergy: 24,
  dtype: 'Physical',
  basedmg: 3,
  dmgvariance: 7,
  maxarmor: 4,
  currarmor: 4,
  maxward: 0,
  currward: 0,
  abilqueue: ['Opening-Volley', 'Feint', 'Overpower', 'Block', 'Counter-Attack'],
  evil: false,
}, {
  name: 'Bugbear Magi',
  illus: 'images/characters/bugbear-magi.gif',
  maxhp: 27,
  currhp: 27,
  maxenergy: 30,
  currenergy: 30,
  dtype: 'Magical',
  basedmg: 6,
  dmgvariance: 4,
  maxarmor: 2,
  currarmor: 2,
  maxward: 3,
  currward: 3,
  abilqueue: ['Spell-Break', 'Lightning-Bolt', 'Cold-Snap', 'Attack', 'Lightning-Bolt'],
  evil: false,
}, {
  name: 'Bugbear Warrior',
  illus: 'images/characters/bugbear-warrior.gif',
  maxhp: 40,
  currhp: 40,
  maxenergy: 25,
  currenergy: 25,
  dtype: 'Physical',
  basedmg: 7,
  dmgvariance: 5,
  maxarmor: 2,
  currarmor: 2,
  maxward: 0,
  currward: 0,
  abilqueue: ['Attack', 'Combo', 'Overpower', 'Feint', 'Attack'],
  evil: false,
}, {
  name: 'Bugbear Ranger',
  illus: 'images/characters/bugbear-ranger.gif',
  maxhp: 35,
  currhp: 35,
  maxenergy: 35,
  currenergy: 35,
  dtype: 'Physical',
  basedmg: 8,
  dmgvariance: 4,
  maxarmor: 1,
  currarmor: 1,
  maxward: 0,
  currward: 0,
  abilqueue: ['Opening-Volley', 'Piercing-Strike', 'Attack', 'Dodge', 'Dodge'],
  evil: false,
}, {
  name: 'Death Knight',
  illus: 'images/characters/death-knight.gif',
  maxhp: 45,
  currhp: 45,
  maxenergy: 20,
  currenergy: 20,
  dtype: 'Physical',
  basedmg: 9,
  dmgvariance: 3,
  maxarmor: 4,
  currarmor: 4,
  maxward: 2,
  currward: 2,
  abilqueue: ['Curse', 'Attack', 'Drain-Life', 'Attack', 'Finisher'],
  evil: true,
}];

var levelarr = [
  ['Wolferine'],
  ['Goblin Archer', 'Goblin Berserker'],
  ['Goblin Archer', 'Goblin Crone', 'Wolferine'],
  ['Imp', 'Tiefling', 'Crazed Gnome'],
  ['Mercenary', 'Rust Monster', 'Gelatinous Cube', 'Imp'],
  ['Bugbear Ranger', 'Bugbear Warrior', 'Bugbear Magi'],
  ['Skeleton', 'Crazed Gnome', 'Skeleton', 'Death Knight'],
  ['Imp', 'Tiefling', 'Imp', 'Tiefling', 'Pit Fiend'],
  ['Goblin Archer', 'Goblin Berserker', 'Goblin Crone', 'Wolferine', 'Bugbear Ranger', 'Bugbear Magi'],
  ['Imp', 'Skeleton', 'Death Knight', 'Pit Fiend']
];
