const monsterarr = [{
  name: 'Tiefling',
  illus: 'images/characters/tiefling.gif',
  maxhp: 15,
  currhp: 15,
  maxenergy: 20,
  currenergy: 20,
  dtype: 'Physical',
  basedmg: 5,
  dmgvariance: 3,
  maxarmor: 1,
  currarmor: 1,
  maxward: 1,
  currward: 1,
  abilqueue: ['Curse', 'Attack', 'Venom-Strike', 'Dodge', 'Attack'],
  evil: true,
}, {
  name: 'Crazed Gnome',
  illus: 'images/characters/crazed-gnome.gif',
  maxhp: 20,
  currhp: 20,
  maxenergy: 25,
  currenergy: 25,
  dtype: 'Magical',
  basedmg: 6,
  dmgvariance: 4,
  maxarmor: 0,
  currarmor: 0,
  maxward: 2,
  currward: 2,
  abilqueue: ['Mote-of-Fire', 'Silence', 'Flame-Wave', 'Drain-Life', 'Attack'],
  evil: false,
}, {
  name: 'Pit Fiend',
  illus: 'images/characters/pit-fiend.gif',
  maxhp: 45,
  currhp: 45,
  maxenergy: 18,
  currenergy: 18,
  dtype: 'Physical',
  basedmg: 8,
  dmgvariance: 6,
  maxarmor: 3,
  currarmor: 3,
  maxward: 1,
  currward: 1,
  abilqueue: ['Doom', 'Feint', 'Attack', 'Combo', 'Finisher'],
  evil: true,
}, {
  name: 'Goblin Archer',
  illus: 'images/characters/goblin-archer.gif',
  maxhp: 12,
  currhp: 12,
  maxenergy: 10,
  currenergy: 10,
  dtype: 'Physical',
  basedmg: 6,
  dmgvariance: 3,
  maxarmor: 0,
  currarmor: 0,
  maxward: 0,
  currward: 0,
  abilqueue: ['Opening-Volley', 'Attack', 'Piercing-Strike', 'Dodge', 'Attack'],
  evil: false,
}, {
  name: 'Goblin Berserker',
  illus: 'images/characters/goblin-berserker.gif',
  maxhp: 22,
  currhp: 22,
  maxenergy: 15,
  currenergy: 15,
  dtype: 'Physical',
  basedmg: 7,
  dmgvariance: 4,
  maxarmor: 2,
  currarmor: 2,
  maxward: 0,
  currward: 0,
  abilqueue: ['Armor-Break', 'Attack', 'Combo', 'Feint', 'Attack'],
  evil: false,
}, {
  name: 'Goblin Crone',
  illus: 'images/characters/goblin-crone.gif',
  maxhp: 17,
  currhp: 17,
  maxenergy: 18,
  currenergy: 18,
  dtype: 'Magical',
  basedmg: 8,
  dmgvariance: 6,
  maxarmor: 0,
  currarmor: 0,
  maxward: 4,
  currward: 4,
  abilqueue: ['Curse', 'Lightning-Bolt', 'Cold-Snap', 'Attack', 'Dodge'],
  evil: false,
}];
